<? $this->placeholder('footer')->captureStart(); ?>
<span class="status">
	<?=$this->translate('CSR_CURRENT_STATUS');?>: 
    <? if(date("N") <= 5 && date("G") >= 8 && date("G") < 17): ?>
    	<span class="green"><?=$this->translate('CSR_AVAILABLE');?></span>
    <? else: ?>
    	<span class="red"><?=$this->translate('CSR_UNAVAILABLE');?></span>
    <? endif; ?>
</span>
<? $this->placeholder('footer')->captureEnd() ?>