<div id="error-wrapper">
<? if($this->errorType == 404): ?>
		<p>Unfortunately the page you are looking for does not exist.</p>
		<p>This may have been caused by one of the following:</p>
		<ul>
	   		<li>If you typed the URL in manually, you may have made a minor mistake when typing in in, check the URL and try again.</li>
			<li>If you were linked to this site from another page, they may have gotten the link wrong or the linked page may no longer exists.</li>
			<li>The page may have moved, you may find it elsewhere on the site.</li>
	   	</ul>
<? elseif($this->errorType == 500): ?>
		<p>There was a temporary problem on the server.</p>
		<p>We are working to resolve this issue.  Please try again shortly.</p>
<? else: ?>
	<p>Oh no......</p>
<? endif; ?>
</div>