<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-US">
<head>
	<title>Sample Module</title>
</head>
<body>

<div id="header">
	<h3>Sample Module (Provided by an add-on)</h3>
</div>

<div class="clearfix">
	<div id="content">
		<?= $this->layout()->content; ?>
	</div>
</div>

<div id="footer">
Cosmos Commerce v <?=Cosmos_Version::VERSION; ?><br/>
</div>

</body>
</html>