<div id="error-wrapper">
<? if($this->errorType == 404): ?>
		<p><?=$this->translate('404_LINE_1');?></p>
		<p><?=$this->translate('404_LINE_2');?>:</p>
		<ul>
	   		<li><?=$this->translate('404_REASON_1');?></li>
			<li><?=$this->translate('404_REASON_2');?></li>
			<li><?=$this->translate('404_REASON_3');?></li>
	   	</ul>
<? elseif($this->errorType == 500): ?>
		<p><?=$this->translate('500_LINE_1');?></p>
		<p><?=$this->translate('500_LINE_2');?></p>
<? else: ?>
	<p><?=$this->translate('UNKNOWN_ERROR');?></p>
<? endif; ?>
</div>