<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-US">
<head>
	<title>Backend Module / Store Management</title>
</head>
<body>

<div id="header">
	<h3>Backend Module Layout</h3>
</div>

<div class="clearfix">
	<div id="content">
		<?= $this->layout()->content; ?>
	</div>
</div>

<div id="footer">
&copy; <?= date('Y'); ?> CosmosCommerce.com
</div>

</body>
</html>