<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-US">
<head>
	<title></title>
</head>
<body>
<? if(Zend_Registry::get('options')->sharedsession->enabled): ?>
<script type="text/javascript" src="http://cosmos/sso?csid=<?= Zend_Session::getId(); ?>"></script>
<? endif; ?>

<div id="header">
	<h3>Storefront Module</h3>
</div>

<div class="clearfix">
	<div id="content">
		<?= $this->layout()->content; ?>
	</div>
</div>

<div id="footer">

<?= $this->placeholder('footer') ?>

<p>Cosmos Commerce v <?=Cosmos_Version::VERSION; ?><br/>
(SESSION: <?= Zend_Session::getId(); ?>)</p>
</div>

</body>
</html>