<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-US">
<head>
	<title>Checkout Module</title>
</head>
<body>
<script type="text/javascript" src="http://cosmos/sso?csid=<?= Zend_Session::getId(); ?>"></script>

<div id="header">
	<h3>Checkout Moduel</h3>
</div>

<div class="clearfix">
	<div id="content">
		<?= $this->layout()->content; ?>
	</div>
</div>

<div id="footer">
&copy; <?= date('Y'); ?> CosmosCommerce.com<br/>
(SESSION: <?= Zend_Session::getId(); ?>)<br/>
(AUTHVALUE: <? var_dump(Zend_Registry::get('csession')->sessionExists); ?>)<br/>
</div>

</body>
</html>