<form method="post" action="<?= $this->url(array('controller' => 'login', 'action' => 'authenticate', 'module' => 'backend')); ?>">
	<fieldset id="login">

		<legend>
			<img src="<?= $this->baseUrl('theme/backend/' . Zend_Registry::get('options')->theme . '/key.png');?>"/> 
			<?= $this->translate('BACKEND_AUTH_REQUIRED');?>
		</legend>
		<table width="190">
			<tr>
				<td colspan="2">
					<ul class="messages"></ul>
				</td>
			</tr>
			<tr>
				<td align="right"><?= $this->translate('USERNAME');?>:</td>
				<td align="right"><input type="text" name="username" /></td>
			</tr>
			<tr>
				<td align="right"><?= $this->translate('PASSWORD');?>:</td>
				<td align="right"><input type="password" name="password" /></td>
			</tr>
			<tr>
				<td colspan="2" align="right"><input type="submit" value="<?= $this->translate('LOGIN_BUTTON');?>" /></td>
			</tr>
		</table>
	</fieldset>
</form>