<form method="post" action="<?= $this->url(array('controller' => 'login', 'action' => 'authenticate', 'module' => 'backend')); ?>">
	<fieldset id="login">

		<legend><img src="<?= $this->baseUrl('theme/backend/' . Zend_Registry::get('options')->theme . '/key.png');?>"/> Authorization Required</legend>
		<table width="190">
			<tr>
				<td colspan="2">
					<ul class="messages"></ul>
				</td>
			</tr>
			<tr>
				<td align="right">Username:</td>
				<td align="right"><input type="text" name="username" /></td>
			</tr>
			<tr>
				<td align="right">Password:</td>
				<td align="right"><input type="password" name="password" /></td>
			</tr>
			<tr>
				<td colspan="2" align="right"><input type="submit" value="Login" /></td>
			</tr>
		</table>
	</fieldset>
</form>